---
apiVersion: tekton.dev/v1beta1
kind: Pipeline # Recipe, PipelineRun needed
metadata:
  name: mohamed-keerthana-nodejs-app-deploy
spec:
  params:
    - name: source-repo
      type: string
      description: Source code repository
    - name: source-image
      type: string
      description: Source image
  workspaces: 
    - name: pipeline-shared-data
  tasks:
    - name: clone-repository
      params:
        - name: url
          value: "$(params.source-repo)"
      workspaces:
        - name: output
          workspace: pipeline-shared-data
      taskRef:
        name: git-clone
    - name: run-tests
      taskRef:
        name: npm
      runAfter:
        - clone-repository
      params:
        - name: ARGS
          value:
            - install-ci-test
      workspaces:
        - name: source # mounted in the directory source in the task
          workspace: pipeline-shared-data # the volume name
    - name: create-image
      runAfter:
        - run-tests
      taskRef:
        name: buildah # build and push
        kind: ClusterTask
      params:
        - name: IMAGE
          value: "$(params.source-image):$(tasks.clone-repository.results.commit)"
      workspaces:
        - name: source
          workspace: pipeline-shared-data # the volume name
  